In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

from sklearn.svm import SVC
sv = SVC()

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [4]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
x1 = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target, cv=3)
x1

array([0.96, 0.96, 0.94])

In [7]:
x2 = cross_val_score(SVC(), iris.data, iris.target, cv=3)
x2

array([0.96, 0.98, 0.94])

In [8]:
x3 = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
x3

array([0.98, 0.94, 0.98])

In [9]:
x4 = cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)
x4

array([0.98, 0.94, 0.94])

In [10]:
x = {'Logistic Regression':x1.mean(), 'Support Vector Machine':x2.mean(), 'Decision Tree':x3.mean(), 'Random Forest':x4.mean()}
print(x)

{'Logistic Regression': 0.9533333333333333, 'Support Vector Machine': 0.96, 'Decision Tree': 0.9666666666666667, 'Random Forest': 0.9533333333333333}
